name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag. fx 1.2.3"
        required: true

jobs:
  process-input:
    runs-on: ubuntu-latest
    outputs:
      validated_version: ${{ steps.validate.outputs.validated_version }}
    steps:
      - name: Validate input
        id: validate
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Input: '$VERSION'"
          
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in the format x.y.z (e.g., 1.2.3)"
            exit 1
          fi
          
          echo "validated_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version is valid ✅"
#      - name: Prepare release tag
#        id: tag
#        run: |
#          VALIDATED_VERSION="${{ steps.validate.outputs.validated_version }}"
#          RELEASE_TAG="v$VALIDATED_VERSION"
#
#          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
#          echo "Prepared release tag: $RELEASE_TAG"

  setup-and-build:
    runs-on: ubuntu-latest
    needs: process-input
    outputs:
      apk_artifact_name: flutter-apk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Apply version to pubspec.yaml
        run: |
          VERSION="${{ needs.process-input.outputs.validated_version }}"
          echo "Applying version $VERSION to pubspec.yaml"
          
          sed -i "0,/^[[:space:]]*version:/c\version: $VERSION" pubspec.yaml
          
          echo "Checking new replace version"
          grep "^version:" pubspec.yaml
