name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag. fx 1.2.3"
        required: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release-tag.outputs.release_tag }}
    steps:
      - name: Validate input
        id: validate
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Input: '$VERSION'"
          
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in the format x.y.z (e.g., 1.2.3)"
            exit 1
          fi
          
          echo "validated_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version is valid ✅"

      - name: Prepare release tag
        id: release-tag
        run: |
          VALIDATED_VERSION="${{ steps.validate.outputs.validated_version }}"
          RELEASE_TAG="v$VALIDATED_VERSION"          

          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Prepared release tag: $RELEASE_TAG"

  checkout-repository:
    runs-on: ubuntu-latest
    needs: create-release-tag
    steps:
      - name: Checkout
        run: |
          echo "Checking out repo"