name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: false
        default: "World"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Manual trigger works!"